import type { Event, BulletinPost } from '../types';

export const STUB_EVENTS: Event[] = [
  {
    id: '1',
    time: '7:00 PM',
    sortKey: 1140,
    event_name: 'Wednesday Night Study',
    location: 'Room 204',
    in_charge: ['John Smith'],
    helpers: ['Sarah Johnson'],
    childcare: [],
    food: [],
    group: 'Youth',
    notes: null,
    raw_tab: '4/7 Tue',
  },
  {
    id: '2',
    time: '9:00 AM',
    sortKey: 540,
    event_name: 'Sunday Rehearsal',
    location: 'Sanctuary',
    in_charge: ['Mike Wilson'],
    helpers: ['Sarah Smith', 'Emily Davis'],
    childcare: [],
    food: [],
    group: 'Worship',
    notes: null,
    raw_tab: '4/7 Tue',
  },
  {
    id: '3',
    time: '10:00 AM',
    sortKey: 600,
    event_name: 'Sunday Childcare',
    location: 'Room 101',
    in_charge: ['Mary Thompson'],
    helpers: [],
    childcare: ['Emma Smith', 'Lucas Johnson'],
    food: [],
    group: 'Kids',
    notes: null,
    raw_tab: '4/7 Tue',
  },
  {
    id: '4',
    time: '4:00 PM',
    sortKey: 960,
    event_name: 'Soccer Practice',
    location: 'Field 2',
    in_charge: ['Coach Dan'],
    helpers: [],
    childcare: [],
    food: [],
    group: 'Kids',
    notes: 'Lucas needs to bring water bottle',
    raw_tab: '4/7 Tue',
  },
  {
    id: '5',
    time: '10:30 AM',
    sortKey: 630,
    event_name: 'Elders meeting',
    location: 'Conference Room',
    in_charge: ['Pastor Dan'],
    helpers: [],
    childcare: [],
    food: [],
    group: null,
    notes: null,
    raw_tab: '4/7 Tue',
  },
  {
    id: '6',
    time: '12:00 PM',
    sortKey: 720,
    event_name: 'Lunch prep',
    location: 'Kitchen',
    in_charge: ['Mary K.'],
    helpers: ['Alice Brown'],
    childcare: [],
    food: ['Sandwiches', 'Salad'],
    group: null,
    notes: null,
    raw_tab: '4/7 Tue',
  },
];

export const STUB_BULLETIN: BulletinPost[] = [
  {
    id: 'b1',
    date: 'Apr 7',
    posted_by: 'Pastor Dan',
    subject: 'Easter schedule change',
    body: 'Sunrise service moved to 6:30 AM. Potluck follows the 10 AM service in the fellowship hall.',
    link_url: 'https://example.com/flyer.pdf',
    link_label: 'Open flyer',
  },
  {
    id: 'b2',
    date: 'Apr 6',
    posted_by: 'Worship Team',
    subject: 'Song list posted',
    body: "This week's setlist is up. Please review before Thursday rehearsal.",
    link_url: 'https://example.com/setlist',
    link_label: 'Open link',
  },
  {
    id: 'b3',
    date: 'Apr 5',
    posted_by: 'Mary K.',
    subject: 'Childcare signups',
    body: 'Two slots still open for next Wednesday. Text me if you can help.',
    link_url: null,
    link_label: null,
  },
];
